### ISSUE TITLE
TypeError: pattern.indexOf is not a function

### ISSUE THREAD

**Issue by josephbergdoll** [Email-builder/grunt-email-builder#49]
Keep getting this and can't figure out the source.

**Comment by jeremypeter** [comment]
@josephbergdoll Can you post your grunt file? Need a little more context

**Comment by josephbergdoll** [comment]
@jeremypeter 

```
emailBuilder:
      inline:
        options:
          encodeSpecialChars: true
        files:
          expand: true
          cwd: 'email/'
          src: ['**/*.html']
          dest: 'email/_inline'
```

**Comment by jeremypeter** [comment]
@josephbergdoll Try this, the `files` property needs to be an array instead of an object:

```
emailBuilder:
      inline:
        options:
          encodeSpecialChars: true
        files: [
          expand: true
          cwd: 'email/'
          src: ['**/*.html']
          dest: 'email/_inline
        ]

```
